#!/bin/sh

echo "clang++ -std=c++11 -Wall -Wextra -o./$1.x -I. -I/home/courses/cop4530p/LIB/cpp -I/home/courses/cop4530p/LIB/tcpp $1.cpp"
clang++ -std=c++11 -Wall -Wextra -o./$1.x -I. -I/home/courses/cop4530p/LIB/cpp -I/home/courses/cop4530p/LIB/tcpp $1.cpp 
